os: linux
dist: trusty
language: node_js
before_install:
  - nvm install 0.10.28
  - nvm use 0.10.28
script:
  - zuul test/wallet.js && npm run-script coverage
after_success:
  - gulp submit-coverage
